#!/bin/bash

## Autostart
~/.config/bspwm/00A &

## Lockscreen
xss-lock -- ~/.config/bspwm/utility/scripts/auto-lock &

xautolock -time 5 -locker "pkill -USR1 xss-lock" \
    -detectsleep -corners ---- &


#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝


bspc monitor -d 1 2 3 4 5 6
bspc desktop -d 7 8 9

## Borderles Windows
bspc config border_width            2
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config focus_follows_pointer   true

## Layout Default
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true

## Theme Borderles
# Inactive window (Black Night)
bspc config normal_border_color   "#0F1115"
# Active (unfocused)
bspc config active_border_color   "#1A1D23"

# Focused window (Forest Green Accent)
bspc config focused_border_color  "#3FA34D"
# Preselect highlight
bspc config presel_feedback_color "#66BB6A"

# Urgent
bspc config urgent_border_color   "#8b2E2E"