#!/usr/bin/bash

# Cek koneksi network
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null 2>&1; then
    ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)
    if [ -n "$ssid" ]; then
        echo "   $ssid"
    else
        echo " ᯤ  Connected"
    fi
else
    echo "   No Network"
fi
