#!/usr/bin/bash

# ambil suhu CPU
temp=$(sensors | awk '/^Package id 0:/ {print $4}' | tr -d '+°C')

# kalo kosong fallback
[ -z "$temp" ] && temp=$(sensors | grep -m 1 '°C' | awk '{print $2}' | tr -d '+°C')

echo " $temp"

