#!/usr/bin/env bash

sleep 0.3

# DBUS
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    log "Not Found D-Bus session, Running dbus-launch..."
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Kill old instances
killall -q polybar dunst
pkill -x sxhkd

while pgrep -u "$UID" -x polybar >/dev/null; do sleep 1; done
while pgrep -u "$UID" -x dunst >/dev/null; do sleep 1; done

# Wallpaper
feh --bg-fill "$HOME/.config/bspwm/wallpapr/Sinon-3.jpg" &

# Start sxhkd properly
sxhkd &

# Picom
~/.config/picom/auto.sh &
~/.config/picom/pause.sh &

# Dunst
dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Monitor hotplug
~/.config/sxhkd/scripts/monitor &
